<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVQAKrL3\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVQAKrL3/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVQAKrL3.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVQAKrL3\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVQAKrL3\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'VQAKrL3',
    'container.build_id' => '3972e8c0',
    'container.build_time' => 1524800153,
));
