<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGTbE8e0\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGTbE8e0/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGTbE8e0.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerGTbE8e0\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerGTbE8e0\srcProdProjectContainer(array(
    'container.build_hash' => 'GTbE8e0',
    'container.build_id' => '260b929e',
    'container.build_time' => 1522465623,
));
