<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPM31cxy\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPM31cxy/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPM31cxy.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPM31cxy\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerPM31cxy\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'PM31cxy',
    'container.build_id' => 'c4660271',
    'container.build_time' => 1524979035,
));
