<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDfc3vaJ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDfc3vaJ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDfc3vaJ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDfc3vaJ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerDfc3vaJ\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Dfc3vaJ',
    'container.build_id' => '6143745f',
    'container.build_time' => 1525036833,
));
