<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container13XUeUW\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container13XUeUW/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container13XUeUW.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container13XUeUW\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container13XUeUW\srcDevDebugProjectContainer(array(
    'container.build_hash' => '13XUeUW',
    'container.build_id' => '68e71394',
    'container.build_time' => 1522539532,
));
